

volumes:
  postgres:


services:
  postgres:
    container_name: qlock_postgres
    image: 'postgres:16.0'
    environment:
      - 'POSTGRES_DB=qlockdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=ojo'
    volumes:
      - postgres:/data/postgres
    ports:
      - '5437:5432'
    restart: on-failure
